export type BlockingService =
  | "cloudflare"
  | "sucuri"
  | "wordfence"
  | "aws-waf"
  | "modsecurity"
  | "unknown";

export interface BlockingDetection {
  service: BlockingService;
  hint: string;
  fixUrl?: string;
}

export interface WooErrorContext {
  url?: string;
  method?: string;
  params?: Record<string, unknown>;
  status?: number;
  body?: string;
  headers?: Record<string, string>;
  blocking_service?: BlockingService;
  blocking_hint?: string;
}

export class WooApiError extends Error {
  context: WooErrorContext;
  constructor(message: string, context: WooErrorContext) {
    super(message);
    this.name = "WooApiError";
    this.context = context;
  }
}

export function isRetryableError(status?: number, errName?: string): boolean {
  if (errName === "AbortError" || errName === "FetchError" || errName === "TypeError") return true;
  if (!status) return true;
  if (status === 408 || status === 429) return true;
  if (status >= 500 && status < 600) return true;
  return false;
}

const BACKOFF_SECONDS = [30, 120, 300, 900];

export function nextRetryDelaySeconds(attempt: number): number | null {
  if (attempt < 1 || attempt > BACKOFF_SECONDS.length) return null;
  return BACKOFF_SECONDS[attempt - 1];
}

export const MAX_SYNC_ATTEMPTS = 5;

export function buildCurlCommand(ctx: WooErrorContext, consumerKey?: string, consumerSecret?: string): string {
  const method = ctx.method || "GET";
  const url = ctx.url || "";
  const key = consumerKey || "$WC_KEY";
  const secret = consumerSecret || "$WC_SECRET";
  return `curl -X ${method} "${url}" -u "${key}:${secret}" -H "Accept: application/json"`;
}

/**
 * Branded User-Agent sent on every outbound WooCommerce / WordPress request.
 * Lets site admins identify and allowlist us, and distinguishes legitimate
 * integration traffic from scraper bots in access logs + WAF telemetry.
 */
const APP_URL =
  process.env.NEXT_PUBLIC_APP_URL ||
  process.env.NEXT_PUBLIC_VERCEL_URL ||
  "https://woosync.app";
export const WOO_USER_AGENT = `Proxima-WooSync/1.0 (+${APP_URL.startsWith("http") ? APP_URL : `https://${APP_URL}`})`;

/**
 * Classifies a failed HTTP response as coming from a known WAF/firewall.
 * Inspects status code, body snippet (first ~2KB is enough), and response headers.
 * Returns null if no known signature matches.
 */
export function detectBlockingService(
  status: number,
  body: string,
  headers: Headers | Record<string, string>
): BlockingDetection | null {
  const lowerBody = (body || "").toLowerCase();
  const h =
    headers instanceof Headers
      ? headers
      : new Headers(Object.entries(headers || {}).map(([k, v]) => [k, String(v)] as [string, string]));

  // Cloudflare — highest confidence, most common
  if (
    h.get("cf-ray") ||
    h.get("cf-mitigated") ||
    lowerBody.includes("just a moment...") ||
    lowerBody.includes('ctype: "managed"') ||
    lowerBody.includes("cf-chl-") ||
    lowerBody.includes("challenges.cloudflare.com")
  ) {
    return {
      service: "cloudflare",
      hint:
        "Cloudflare is serving a Managed Challenge or Bot Fight Mode interstitial for WooCommerce API requests. The site admin must add a WAF Custom Rule that skips managed rules for /wp-json/* paths.",
      fixUrl: "https://developers.cloudflare.com/waf/custom-rules/skip/",
    };
  }

  // Sucuri Firewall
  if (
    h.get("x-sucuri-id") ||
    h.get("x-sucuri-cache") ||
    lowerBody.includes("access denied - sucuri") ||
    lowerBody.includes("sucuri website firewall")
  ) {
    return {
      service: "sucuri",
      hint:
        "Sucuri Website Firewall is blocking API requests. Site admin must allowlist our outbound IPs (or User-Agent) in the Sucuri Firewall dashboard under Security → Access Control.",
      fixUrl: "https://docs.sucuri.net/website-firewall/settings/access-control/",
    };
  }

  // WordFence
  if (
    lowerBody.includes("your access to this site has been limited") ||
    lowerBody.includes("wordfence") ||
    lowerBody.includes("generated by wordfence")
  ) {
    return {
      service: "wordfence",
      hint:
        "WordFence firewall is blocking API requests. Site admin must allowlist our User-Agent or IP in WordFence → Tools → Diagnostics → Allowlisted URLs / IPs.",
      fixUrl:
        "https://www.wordfence.com/help/firewall/options/#whitelisted-urls",
    };
  }

  // AWS WAF
  if (
    h.get("x-amzn-requestid") ||
    h.get("x-amz-apigw-id") ||
    (status === 403 && lowerBody.includes("request blocked"))
  ) {
    return {
      service: "aws-waf",
      hint:
        "AWS WAF is blocking API requests. Site admin must add a WebACL exception rule for /wp-json/* paths or allowlist our User-Agent.",
      fixUrl:
        "https://docs.aws.amazon.com/waf/latest/developerguide/waf-rule-exceptions.html",
    };
  }

  // ModSecurity / generic cPanel
  if (
    lowerBody.includes("not acceptable!") ||
    lowerBody.includes("mod_security") ||
    lowerBody.includes("406 not acceptable") ||
    (status === 406 && lowerBody.includes("apache"))
  ) {
    return {
      service: "modsecurity",
      hint:
        "ModSecurity (typically cPanel or Apache-based hosting) is blocking API requests. Site admin must disable the offending rule ID or allowlist our User-Agent via their hosting control panel.",
    };
  }

  // Unknown 403 with no matching signature — still useful to surface
  if (status === 403) {
    return {
      service: "unknown",
      hint:
        "The site returned 403 Forbidden with no recognized WAF signature. Check the site's security plugins, hosting firewall, and server access logs for blocked requests from our User-Agent.",
    };
  }

  return null;
}