export type BlockingService =
  | "cloudflare"
  | "sucuri"
  | "wordfence"
  | "aws-waf"
  | "modsecurity"
  | "unknown";

export interface BlockingDetection {
  service: BlockingService;
  hint: string;
  fixUrl?: string;
}

export interface WooErrorContext {
  url?: string;
  method?: string;
  params?: Record<string, unknown>;
  status?: number;
  body?: string;
  headers?: Record<string, string>;
  blocking_service?: BlockingService;
  blocking_hint?: string;
}

export class WooApiError extends Error {
  context: WooErrorContext;
  constructor(message: string, context: WooErrorContext) {
    super(message);
    this.name = "WooApiError";
    this.context = context;
  }
}

export function isRetryableError(status?: number, errName?: string): boolean {
  if (errName === "AbortError" || errName === "FetchError" || errName === "TypeError") return true;
  if (!status) return true;
  if (status === 408 || status === 429) return true;
  if (status >= 500 && status < 600) return true;
  return false;
}

const BACKOFF_SECONDS = [30, 120, 300, 900];

export function nextRetryDelaySeconds(attempt: number): number | null {
  if (attempt < 1 || attempt > BACKOFF_SECONDS.length) return null;
  return BACKOFF_SECONDS[attempt - 1];
}

export const MAX_SYNC_ATTEMPTS = 5;

export function buildCurlCommand(ctx: WooErrorContext, consumerKey?: string, consumerSecret?: string): string {
  const method = ctx.method || "GET";
  const url = ctx.url || "";
  const key = consumerKey || "$WC_KEY";
  const secret = consumerSecret || "$WC_SECRET";
  return `curl -X ${method} "${url}" -u "${key}:${secret}" -H "Accept: application/json"`;
}

const APP_URL =
  process.env.NEXT_PUBLIC_APP_URL ||
  process.env.NEXT_PUBLIC_VERCEL_URL ||
  "https://woosync.app";
const APP_URL_NORMALIZED = APP_URL.startsWith("http") ? APP_URL : `https://${APP_URL}`;
export const WOO_USER_AGENT = `Proxima-WooSync/1.0 (+${APP_URL_NORMALIZED})`;

export function detectBlockingService(
  status: number,
  body: string,
  headers: Headers | Record<string, string>
): BlockingDetection | null {
  const lowerBody = (body || "").toLowerCase();
  const h =
    headers instanceof Headers
      ? headers
      : new Headers(Object.entries(headers || {}).map(([k, v]) => [k, String(v)] as [string, string]));

  if (
    h.get("cf-ray") ||
    h.get("cf-mitigated") ||
    lowerBody.includes("just a moment...") ||
    lowerBody.includes('ctype: "managed"') ||
    lowerBody.includes("cf-chl-") ||
    lowerBody.includes("challenges.cloudflare.com")
  ) {
    return {
      service: "cloudflare",
      hint:
        "Cloudflare is serving a Managed Challenge or Bot Fight Mode interstitial. The site admin must add a WAF Custom Rule that skips managed rules for /wp-json/* paths.",
      fixUrl: "https://developers.cloudflare.com/waf/custom-rules/skip/",
    };
  }

  if (
    h.get("x-sucuri-id") ||
    h.get("x-sucuri-cache") ||
    lowerBody.includes("access denied - sucuri") ||
    lowerBody.includes("sucuri website firewall")
  ) {
    return {
      service: "sucuri",
      hint:
        "Sucuri Website Firewall is blocking API requests. Site admin must allowlist our outbound IPs or User-Agent in the Sucuri Firewall dashboard.",
      fixUrl: "https://docs.sucuri.net/website-firewall/settings/access-control/",
    };
  }

  if (
    lowerBody.includes("your access to this site has been limited") ||
    lowerBody.includes("wordfence") ||
    lowerBody.includes("generated by wordfence")
  ) {
    return {
      service: "wordfence",
      hint:
        "WordFence firewall is blocking API requests. Site admin must allowlist our User-Agent or IP in WordFence → Tools → Diagnostics → Allowlisted URLs / IPs.",
      fixUrl: "https://www.wordfence.com/help/firewall/options/#whitelisted-urls",
    };
  }

  if (
    h.get("x-amzn-requestid") ||
    h.get("x-amz-apigw-id") ||
    (status === 403 && lowerBody.includes("request blocked"))
  ) {
    return {
      service: "aws-waf",
      hint:
        "AWS WAF is blocking API requests. Site admin must add a WebACL exception for /wp-json/* paths or allowlist our User-Agent.",
      fixUrl: "https://docs.aws.amazon.com/waf/latest/developerguide/waf-rule-exceptions.html",
    };
  }

  if (
    lowerBody.includes("not acceptable!") ||
    lowerBody.includes("mod_security") ||
    lowerBody.includes("406 not acceptable") ||
    (status === 406 && lowerBody.includes("apache"))
  ) {
    return {
      service: "modsecurity",
      hint:
        "ModSecurity (typical on cPanel / Apache hosting) is blocking API requests. Site admin must disable the offending rule ID or allowlist our User-Agent.",
    };
  }

  if (status === 403) {
    return {
      service: "unknown",
      hint:
        "Site returned 403 Forbidden with no recognized WAF signature. Check active security plugins, hosting firewall, and server access logs.",
    };
  }

  return null;
}