export type VariableItem = { token: string; desc: string };
export type VariableGroup = { label: string; items: VariableItem[] };

export const VARIABLE_GROUPS: VariableGroup[] = [
  { label: "Order", items: [
    { token: "{{order.number}}", desc: "Order number" },
    { token: "{{order.date}}", desc: "Formatted order date" },
    { token: "{{order.date_iso}}", desc: "ISO timestamp (use with date helper)" },
    { token: "{{order.status}}", desc: "Status (processing, completed…)" },
    { token: "{{order.currency}}", desc: "ISO currency code" },
    { token: "{{order.currency_symbol}}", desc: "Currency symbol" },
    { token: "{{order.notes}}", desc: "Customer note" },
    { token: "{{order.transaction_id}}", desc: "Gateway transaction ID" },
    { token: "{{order.payment_method}}", desc: "Payment method slug" },
    { token: "{{order.payment_method_title}}", desc: "Payment method label" },
    { token: "{{order.total}}", desc: "Order total (raw)" },
    { token: "{{order.subtotal}}", desc: "Items subtotal (raw)" },
    { token: "{{order.tax_total}}", desc: "Total tax (raw)" },
    { token: "{{order.shipping_total}}", desc: "Shipping total (raw)" },
    { token: "{{order.discount_total}}", desc: "Discount total (raw)" },
  ]},
  { label: "Customer", items: [
    { token: "{{customer.id}}", desc: "Customer ID" },
    { token: "{{customer.name}}", desc: "Full name" },
    { token: "{{customer.first_name}}", desc: "First name" },
    { token: "{{customer.last_name}}", desc: "Last name" },
    { token: "{{customer.email}}", desc: "Email" },
    { token: "{{customer.phone}}", desc: "Phone" },
  ]},
  { label: "Billing", items: [
    { token: "{{billing.name}}", desc: "Full name" },
    { token: "{{billing.first_name}}", desc: "First name" },
    { token: "{{billing.last_name}}", desc: "Last name" },
    { token: "{{billing.email}}", desc: "Email" },
    { token: "{{billing.phone}}", desc: "Phone" },
    { token: "{{billing.company}}", desc: "Company" },
    { token: "{{billing.address.line1}}", desc: "Street line 1" },
    { token: "{{billing.address.line2}}", desc: "Street line 2" },
    { token: "{{billing.city}}", desc: "City" },
    { token: "{{billing.state}}", desc: "State / region" },
    { token: "{{billing.zip}}", desc: "Postal code" },
    { token: "{{billing.country}}", desc: "Country" },
    { token: "{{address billing}}", desc: "Render full block (helper)" },
  ]},
  { label: "Shipping", items: [
    { token: "{{shipping.name}}", desc: "Full name" },
    { token: "{{shipping.first_name}}", desc: "First name" },
    { token: "{{shipping.last_name}}", desc: "Last name" },
    { token: "{{shipping.company}}", desc: "Company" },
    { token: "{{shipping.address.line1}}", desc: "Street line 1" },
    { token: "{{shipping.address.line2}}", desc: "Street line 2" },
    { token: "{{shipping.city}}", desc: "City" },
    { token: "{{shipping.state}}", desc: "State / region" },
    { token: "{{shipping.zip}}", desc: "Postal code" },
    { token: "{{shipping.country}}", desc: "Country" },
    { token: "{{address shipping}}", desc: "Render full block (helper)" },
  ]},
  { label: "Payment", items: [
    { token: "{{payment.method}}", desc: "Method slug" },
    { token: "{{payment.title}}", desc: "Method label" },
    { token: "{{payment.status}}", desc: "Payment status" },
    { token: "{{payment.transaction_id}}", desc: "Gateway transaction ID" },
  ]},
  { label: "Shipping method", items: [
    { token: "{{shipping_method.name}}", desc: "Carrier / method name" },
    { token: "{{shipping_method.tracking_number}}", desc: "Tracking number" },
  ]},
  { label: "Totals", items: [
    { token: "{{totals.subtotal}}", desc: "Items subtotal" },
    { token: "{{totals.discount}}", desc: "Discount amount" },
    { token: "{{totals.shipping}}", desc: "Shipping cost" },
    { token: "{{totals.tax}}", desc: "Tax amount" },
    { token: "{{totals.total}}", desc: "Grand total" },
  ]},
  { label: "Items (loop)", items: [
    { token: "{{#each items}}", desc: "Open items loop" },
    { token: "{{name}}", desc: "Item name (inside loop)" },
    { token: "{{sku}}", desc: "SKU" },
    { token: "{{quantity}}", desc: "Quantity" },
    { token: "{{qty}}", desc: "Quantity (alias)" },
    { token: "{{price}}", desc: "Unit price" },
    { token: "{{subtotal}}", desc: "Line subtotal" },
    { token: "{{total}}", desc: "Line total" },
    { token: "{{image}}", desc: "Product image URL" },
    { token: "{{variation_text}}", desc: "All attributes joined ('Size: M, Color: Blue')" },
    { token: "{{variation.size}}", desc: "Specific attribute (lowercased key)" },
    { token: "{{variation.color}}", desc: "Specific attribute" },
    { token: "{{/each}}", desc: "Close items loop" },
  ]},
  { label: "Store", items: [
    { token: "{{store.name}}", desc: "Store name" },
    { token: "{{store.logo}}", desc: "Logo URL" },
    { token: "{{store.email}}", desc: "Support email" },
    { token: "{{store.phone}}", desc: "Phone" },
    { token: "{{store.website}}", desc: "Website URL" },
    { token: "{{store.url}}", desc: "Storefront URL" },
    { token: "{{store.currency}}", desc: "Default currency" },
    { token: "{{store.address.line1}}", desc: "Address line 1" },
    { token: "{{store.address.line2}}", desc: "Address line 2" },
    { token: "{{store.address.city}}", desc: "City" },
    { token: "{{store.address.state}}", desc: "State" },
    { token: "{{store.address.country}}", desc: "Country" },
    { token: "{{store.address.zip}}", desc: "Zip" },
  ]},
  { label: "Meta", items: [
    { token: "{{meta.note}}", desc: "Customer note" },
    { token: "{{meta.gift_message}}", desc: "Gift message (from order meta)" },
    { token: "{{meta.delivery_date}}", desc: "Delivery date (from order meta)" },
    { token: "{{meta.custom_field_1}}", desc: "Custom field 1" },
    { token: "{{meta.custom_field_2}}", desc: "Custom field 2" },
    { token: "{{meta.printed_at}}", desc: "Print timestamp" },
    { token: "{{meta.template_name}}", desc: "Template name" },
    { token: "{{meta.template_type}}", desc: "Template type" },
  ]},
  { label: "Report (report templates)", items: [
    { token: "{{report.title}}", desc: "Report title" },
    { token: "{{report.generated_at}}", desc: "Generation timestamp" },
    { token: "{{report.period_label}}", desc: "Period description" },
    { token: "{{report.currency}}", desc: "Currency for amounts" },
    { token: "{{#each rows}}", desc: "Start order rows" },
    { token: "{{order_number}}", desc: "Order number (in row)" },
    { token: "{{date}}", desc: "Row date" },
    { token: "{{customer}}", desc: "Customer name" },
    { token: "{{total}}", desc: "Order total (numeric)" },
    { token: "{{status}}", desc: "Order status" },
    { token: "{{currency total ../report.currency}}", desc: "Format row total" },
    { token: "{{/each}}", desc: "End rows" },
    { token: "{{summary.order_count}}", desc: "Number of orders" },
    { token: "{{summary.revenue}}", desc: "Sum of totals" },
    { token: "{{currency summary.revenue report.currency}}", desc: "Formatted revenue" },
  ]},
  { label: "Helpers", items: [
    { token: "{{currency totals.total}}", desc: "Format money (uses order currency)" },
    { token: "{{currency totals.total order.currency}}", desc: "Format with explicit currency" },
    { token: "{{formatCurrency totals.total}}", desc: "Alias of currency" },
    { token: '{{date order.date_iso "short"}}', desc: "Format date (short/long/iso/datetime/time)" },
    { token: "{{formatDate order.date_iso}}", desc: "Alias of date" },
    { token: "{{barcode order.number}}", desc: "Render barcode SVG (use format=, width=, height=)" },
    { token: "{{qrcode order.number size=120}}", desc: "Render QR code image" },
    { token: '{{#ifCond order.status "completed"}}…{{else}}…{{/ifCond}}', desc: "Conditional equality block" },
    { token: "{{#if (gt totals.discount 0)}}…{{/if}}", desc: "Conditional with comparator (eq/neq/gt/lt/gte/lte)" },
    { token: "{{multiply price quantity}}", desc: "Math (multiply/add/subtract/divide)" },
    { token: "{{uppercase order.status}}", desc: "Uppercase / lowercase / capitalize / titlecase" },
    { token: '{{default customer.phone "—"}}', desc: "Fallback for empty value" },
    { token: "{{concat store.url '/orders/' order.number}}", desc: "Concatenate strings" },
  ]},
];
