 
// This file is automatically generated. Do not edit it directly.
// Types are generated from the Supabase database schema.
import { Database as DatabaseGenerated } from "./database.types";

export type Database = DatabaseGenerated;
export type Tables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Row"];
export type TablesInsert<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Insert"];
export type TablesUpdate<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Update"];
export type Enums<T extends keyof Database["public"]["Enums"]> =
  Database["public"]["Enums"][T];

// Project reference: zhsmlfdmtlzyxvioppex